Diagrama de Pacote Frontend
UNB-PI2-Grupo3-BracoRobotico/Documentation pull request #20
Opened 2023-04-23 20:37 UTC by MauricioMachadoFF

2023-04-24 20:50 UTC, fernandes-natanael commented
Entao, pelo q vi rapidamente o diagrama de pacotes parece bem detalhado, so senti um pouco de falta de falar sobre o Clean architecture, no caso seria o modelo adotado?

2023-04-26 14:04 UTC, fernandes-natanael requested changes
Além dos pontos ressaltado, acredito que neste caso seria o documento relacionado apenas ao diagrama de pacotes. por possuir um h1 Diagrama de Pacotes, entao mudar o nome apresentado na nav bar e o nome do arquivo.

Ou deixar claro que se trata do documento de arquitetura e separar como topico do mesmo

2023-04-26 14:04 UTC, fernandes-natanael commented on docs/documento_arquitetura.md
> +# Diagrama de Pacote (Front-End)
tem 2 H1, o de Introducao e Diagrama de Pacotes

2023-04-27 01:15 UTC, DaviMatheus commented
Por mim não achei nenhum erro, agora só falta a correção ortográfica que o natanael apontou @MauricioMachadoFF

2023-04-27 19:08 UTC, MauricioMachadoFF commented on docs/documento_arquitetura.md
> +# Diagrama de Pacote (Front-End)
Isso está correto os Headers 1 vão servir pra isso. Os artefatos produzidos e itens como introdução conclusão e referências

2023-04-28 00:16 UTC, DaviMatheus approved these changes

2023-04-28 00:33 UTC, PedroMoraes39 approved these changes

2023-04-28 00:34 UTC, merged