Refac/diagramas de uso
UNB-PI2-Grupo3-BracoRobotico/Documentation pull request #48
Opened 2023-05-12 11:04 UTC by MauricioMachadoFF

2023-05-18 16:01 UTC, DaviMatheus reviewed
Por mim está muito bem detalhado, fora o erro da crase na minha visão o documento está muito bom

2023-05-18 19:08 UTC, MauricioMachadoFF commented on docs/documento_requisito.md
> +|     **Requisitos**      |                                                                                                                                                            Acesso a interne
Solved by [f0cfc2d](https://github.com/UNB-PI2-Grupo3-BracoRobotico/Documentation/pull/48/commits/f0cfc2d0fc5d5b6ba9d1d53698868392eeecaa4f)

2023-05-18 22:23 UTC, fernandes-natanael requested changes
acho q no que esta escrito ta ok, os problemas q achei foram nos diagramas.

- Estoquista ta escito incorreto.
- Diagrama de compra esta com titulo de estoque.
- Nao sei o quao criterioso os professore serao com a escrita mas acho q seria interessante mudar o seguinte:
  - Separar a Gerencia do carrinho em tres casos.
  - no mesmo diagrama o "usar metodo de pagamento", acredito nao ser um caso de uso dessa forma, acho que seria melhor usar "Pagar com metodo já pré-cadastrado".

2023-05-20 01:04 UTC, fernandes-natanael approved these changes

2023-05-20 18:24 UTC, merged