Refac/diagrama entidade relacional
UNB-PI2-Grupo3-BracoRobotico/Documentation pull request #52
Opened 2023-05-22 12:10 UTC by PedroMoraes39

2023-05-22 13:29 UTC, MauricioMachadoFF commented
Quanto ao diagrama entidade relacional:

- Use o símbolo de especficação no diagrama entidade relacionamento. Que é o triângulo (dá uma pesquisada pra ver)
- Estoquista deve ter alguma credecial único além do cpf para operação do sistema.
- Sobre relacionamento entre `Produto` e `Inventário`. Não está muito claro qual registra qual. Usar setas ou cardinalidade.
- Sobre entidades Carrinho e Carrinho Grupo. Como classes acredito que faça sentido serem duas classes, mas no banco de dados podemos tornar apenas uma tabela de classes que tenha a coluna `isGroupCart` ou algo do gênero. Além disso, adicionar id para os carrinhos
- Feedback geral: Nome dos relacionmentos está genérico e não deixa claro qual o agente da relação. Melhorar esses nomes

2023-05-23 16:40 UTC, DaviMatheus reviewed
Senti falta de cardinalidade nas setas e também em qual direção elas estão apontando,  Tem um texto falando q teram somente tres no banco tem que alterar isso.
Mas em geral achei muito confuso o DER 
Um exemplo para deixar mais organizado: 

![der](https://github.com/UNB-PI2-Grupo3-BracoRobotico/Documentation/assets/54643148/9f7a9e21-78d9-481b-808a-ea1aaec5daad)

2023-05-25 13:43 UTC, fernandes-natanael requested changes
Seria bom remover o retangulo estoque do DER, pq da uma falsa impressao de q estoque eh uma entidade

2023-05-25 13:43 UTC, fernandes-natanael commented on docs/documento_arquitetura.md
> +![Modelo Relacional v1.0](assents/../assets/documento_arquitetura/modelagem_relacionalV2.png)
Ta quebrado esse link

2023-05-25 13:51 UTC, MauricioMachadoFF commented
Pontos de alteração:

- Classe `Carrinho` pode possuir mais de um tipo de produto, assim não colocamos o ID do produto é multivalorado. Representar multivalorado na propriedade.
- Consumidor e Estoquista já possuem o cpf do usuário. Não precisamos inserir de novo.

2023-05-25 13:58 UTC, MauricioMachadoFF commented
Sobre modelo relacional:

- Erro de português na entidade `Pagamentos`
- Uso de inglês e português no documento - Use somente português
- Mesmo pontos apontados no DER devem ser arrumados aqui
  - cpf em estoquista e consumidor
  - lista de produtos em carrinho

2023-05-27 17:02 UTC, MauricioMachadoFF approved these changes

2023-05-27 17:42 UTC, merged